In [16]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , classification_report
from sklearn. compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("D:\Crop Prediction System\Model\Datasets\Crop_recommendation.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\premr\AppData\Local\Temp\ipykernel_4840\175953075.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv("D:\Crop Prediction System\Model\Datasets\Crop_recommendation.csv")

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [4]:
df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [5]:
df.isnull().mean()*100

N              0.0
P              0.0
K              0.0
temperature    0.0
humidity       0.0
ph             0.0
rainfall       0.0
label          0.0
dtype: float64

In [6]:
df.duplicated().mean()*100

np.float64(0.0)

In [9]:
df1 = df.groupby("label").count()
df1

               N    P    K  temperature  humidity   ph  rainfall
label
apple        100  100  100          100       100  100       100
banana       100  100  100          100       100  100       100
blackgram    100  100  100          100       100  100       100
chickpea     100  100  100          100       100  100       100
coconut      100  100  100          100       100  100       100
coffee       100  100  100          100       100  100       100
cotton       100  100  100          100       100  100       100
grapes       100  100  100          100       100  100       100
jute         100  100  100          100       100  100       100
kidneybeans  100  100  100          100       100  100       100
lentil       100  100  100          100       100  100       100
maize        100  100  100          100       100  100       100
mango        100  100  100          100       100  100       100
mothbeans    100  100  100          100       100  100       100
mungbean     100  100  100          100       100  100       100
muskmelon    100  100  100          100       100  100       100
orange       100  100  100          100       100  100       100
papaya       100  100  100          100       100  100       100
pigeonpeas   100  100  100          100       100  100       100
pomegranate  100  100  100          100       100  100       100
rice         100  100  100          100       100  100       100
watermelon   100  100  100          100       100  100       100

In [8]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='str')

In [10]:
X = df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]

In [11]:
y = df["label"]

In [12]:
X_train, X_test ,y_train , y_test = train_test_split(X , y , test_size=0.3,random_state=42, stratify=y)

In [13]:
numerical_feat = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
preproccesor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(),numerical_feat)
        ]
)

In [17]:
pipline =Pipeline(
    steps=[
        ("preproccesor", preproccesor),
        ("model", RandomForestClassifier(n_estimators=100, random_state=42, class_weight="balanced"))
    ]
)

In [18]:
pipline.fit(X_train,y_train)

Pipeline(steps=[('preproccesor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['N', 'P', 'K', 'temperature',
                                                   'humidity', 'ph',
                                                   'rainfall'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        random_state=42))])

In [20]:
y_pred = pipline.predict(X_test)
probabilities = pipline.predict_proba(X_test)
mean_test_confidence= probabilities.max(axis=1).mean()*100
test_accuracy=accuracy_score(y_test,y_pred)*100
report = classification_report(y_test,y_pred)

In [21]:
print("***************Model Diagnostic********************")
print("confidence:",mean_test_confidence)
print("accuracy:", test_accuracy)
print("classification_report:", report)

***************Model Diagnostic********************
confidence: 95.07121212121211
accuracy: 99.54545454545455
classification_report:               precision    recall  f1-score   support

       apple       1.00      1.00      1.00        30
      banana       1.00      1.00      1.00        30
   blackgram       1.00      0.97      0.98        30
    chickpea       1.00      1.00      1.00        30
     coconut       1.00      1.00      1.00        30
      coffee       1.00      1.00      1.00        30
      cotton       1.00      1.00      1.00        30
      grapes       1.00      1.00      1.00        30
        jute       0.97      1.00      0.98        30
 kidneybeans       1.00      1.00      1.00        30
      lentil       1.00      0.97      0.98        30
       maize       0.97      1.00      0.98        30
       mango       1.00      1.00      1.00        30
   mothbeans       0.97      1.00      0.98        30
    mungbean       1.00      1.00      1.00        30
   muskmelon       1.00      1.00      1.00        30
      orange       1.00      1.00      1.00        30
      papaya       1.00      1.00      1.00        30
  pigeonpeas       1.00      1.00      1.00        30
 pomegranate       1.00      1.00      1.00        30
        rice       1.00      0.97      0.98        30
  watermelon       1.00      1.00      1.00        30

    accuracy                           1.00       660
   macro avg       1.00      1.00      1.00       660
weighted avg       1.00      1.00      1.00       660

In [ ]:
joblib.dump(pipline, 'Crop_recommendation.pkl')

['Crop_recommendation.pkl']